//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.Tariffbazaar.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceContactDetail
    {
        public int PlaceContactID { get; set; }
        public Nullable<System.Guid> PlaceID { get; set; }
        public string PrimaryPOCName { get; set; }
        public string PrimaryPOCNumber { get; set; }
        public string SecondaryPOCName { get; set; }
        public string SecondaryPOCNumber { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
