//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.Tariffbazaar.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Place()
        {
            this.PlaceContactDetails = new HashSet<PlaceContactDetail>();
            this.PlaceFoodMenus = new HashSet<PlaceFoodMenu>();
            this.PlaceOwnerDetails = new HashSet<PlaceOwnerDetail>();
            this.PlacePriceDetails = new HashSet<PlacePriceDetail>();
            this.PlacesProps = new HashSet<PlacesProp>();
            this.PlaceAddresses = new HashSet<PlaceAddress>();
            this.PlaceImages = new HashSet<PlaceImage>();
        }
    
        public System.Guid PlaceID { get; set; }
        public string Name { get; set; }
        public string SeatingCapacity { get; set; }
        public string DiningCapacity { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<System.DateTime> AvailableFrom { get; set; }
        public Nullable<System.DateTime> AvailableTill { get; set; }
        public Nullable<int> PlaceType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceContactDetail> PlaceContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceFoodMenu> PlaceFoodMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceOwnerDetail> PlaceOwnerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacePriceDetail> PlacePriceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacesProp> PlacesProps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceAddress> PlaceAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceImage> PlaceImages { get; set; }
    }
}
