//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.Tariffbazaar.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceAddress
    {
        public int PlaceAddressID { get; set; }
        public Nullable<System.Guid> PlaceID { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string LandMark { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> Country { get; set; }
        public string LongLatDetails { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string WebsiteLink { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
