//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.Tariffbazaar.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TariffBazaarEntities : DbContext
    {
        public TariffBazaarEntities()
            : base("name=TariffBazaarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<OtpHolder> OtpHolders { get; set; }
        public virtual DbSet<PlaceContactDetail> PlaceContactDetails { get; set; }
        public virtual DbSet<PlaceEvent> PlaceEvents { get; set; }
        public virtual DbSet<PlaceFoodMenu> PlaceFoodMenus { get; set; }
        public virtual DbSet<PlaceOwnerDetail> PlaceOwnerDetails { get; set; }
        public virtual DbSet<PlacePriceDetail> PlacePriceDetails { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PlacesProp> PlacesProps { get; set; }
        public virtual DbSet<RentBasi> RentBasis { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserName> UserNames { get; set; }
        public virtual DbSet<PlaceType> PlaceTypes { get; set; }
        public virtual DbSet<FoodType> FoodTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<PlaceAddress> PlaceAddresses { get; set; }
        public virtual DbSet<PlaceImage> PlaceImages { get; set; }
    }
}
